form/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'cars'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.login, {'template_name': 'login/index.html'}, name='login'),
    path('logout/', auth_views.logout, {'template_name': 'login/index.html'}, name='logout'),
    path('models/', views.models, name='models'),
    path('models/<int:model_id>/', views.choices, name='vehicles'),
    path('models/<int:model_id>/vehicle/<int:vehicle_id>/', views.detail, name='detail'),
    path('models/<int:model_id>/vehicle/<int:vehicle_id>/rent/', views.rent, name='rent'),
    path('rentals/return/<int:vehicle_id>/', views.v_return, name='return'),
    path('accounts/profile/', views.model_redirect),
    path('rentals/', views.rentals, name='rentals'),
]

formlab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('form.urls')),
    path('admin/', admin.site.urls),
]

form/models.py
from django.db import models
from django.conf import settings

class CarModel(models.Model):
    model_type = models.CharField(max_length=200)
    rental_price = models.DecimalField(max_digits=4, default=19.95, decimal_places=2)

    def __str__(self):
        return self.model_type

class Vehicle(models.Model):
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE)
    make = models.CharField(max_length=200, default=None)
    start_date = models.DateField('starting date', default=None, null=True)
    return_date = models.DateField('return date', default=None, null=True)
    mileage = models.IntegerField(default=0)
    renter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.make

form/views.py
from django.shortcuts import get_object_or_404, get_list_or_404, render, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.template import loader
from django.urls import reverse
import datetime as dt

from .models import CarModel
from .models import Vehicle

def index(request):
    return HttpResponse("Hello, world!")

def models(request):
    models = get_list_or_404(CarModel)
    template = loader.get_template('carModels/index.html')
    context = {
        'models': models,
    }
    return HttpResponse(template.render(context, request))

def choices(request, model_id):
    vehicles = get_list_or_404(Vehicle, model_id=model_id)
    model = get_object_or_404(CarModel, id=model_id)
    today = dt.date.today()
    return render(request, 'vehicles/index.html', {'model': model, 'vehicles': vehicles, 'today': today})

def detail(request, model_id, vehicle_id):
    vehicle = get_object_or_404(Vehicle, id=vehicle_id)
    model = get_object_or_404(CarModel, id=model_id)
    return render(request, 'vehicle/index.html', {'model': model, 'vehicle': vehicle})

def rentals(request):
    vehicles = get_list_or_404(Vehicle, renter=request.user)
    model = get_list_or_404(CarModel)
    today = dt.date.today()
    return render(request, 'rentals/index.html', {'vehicles': vehicles, 'today': today, 'model': model})

def rent(request, model_id, vehicle_id):
    # vehicle = get_object_or_404(Vehicle, id=vehicle_id)
    # model = get_object_or_404(CarModel, id=model_id)
    try:
        vehicle = Vehicle.objects.get(id=request.POST.get('vehicle_choice'))
        start_date = request.POST.get('start_date')
        return_date = request.POST.get('return_date')
    except (KeyError, Vehicle.DoesNotExist):
        return render(request, 'vehicle/index.html', {
            'model': model,
            'vehicle': vehicle,
            'error_message': 'It appears this vehicle is no longer available.'
        })
    else:
        vehicle.available = not vehicle.available
        vehicle.start_date = dt.date.today()
        vehicle.return_date = return_date
        vehicle.renter = request.user
        vehicle.save()
        return HttpResponseRedirect(reverse('cars:models'))
    return

def v_return(request, vehicle_id):
    try:
        vehicle = Vehicle.objects.get(id=request.POST.get('vehicle_choice'))
        start_mileage = vehicle.mileage
        mileage = request.POST.get('return_mileage')
    except (KeyError, Vehicle.DoesNotExist):
        return render(request, 'rentals/index.html', {
            'vehicle': vehicle,
            'error_message': 'It appears this vehicle was already returned.'
        })
    else:
        vehicle.available = not vehicle.available
        vehicle.mileage = int(mileage)
        vehicle.start_date = None
        vehicle.return_date = None
        vehicle.renter = None
        vehicle.save()
        return HttpResponseRedirect(reverse('cars:rentals'))
    return

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('models')
    else:
        form = UserCreationForm()
    return render(request, 'signup/index.html', {'form': form})

def model_redirect(request):
    return HttpResponseRedirect(reverse('cars:models'))

form/templates/base/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Car Rentals{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    {% load static %}
    <script src="{% static 'scripts/script.js' %}"></script>
  </head>
  <body>
    <header>
    <div class="row">
        <div class="col s10 offset-s1">
          <h1>Car Rentals</h1>
          {% if user.is_authenticated %}
          <a href={% url 'cars:logout' %}>logout</a> | <a href={% url 'cars:rentals' %}>your rentals</a>
          {% else %}
            <a href={% url 'cars:login' %}>login</a> / <a href={% url 'cars:signup' %}>signup</a>
          {% endif %}
          <hr/>
        </div>
      </div>
    </header>
    <main>
      <div class="row">
        <div class="col s10 offset-s1">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </main>
  </body>
</html>

form/templates/carModels/index.html
{% extends 'base/index.html' %}

{% block content %}
    {% if models %}
        <ul>
            {% for model in models %}
                <li><a href={% url 'cars:vehicles' model.id %}>{{ model.model_type}}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No Cars are available.</p>
    {% endif %}
{% endblock %}

form/templates/login/index.html
{% extends 'base/index.html' %}

{% block content %}
  <h2>Log in to My Site</h2>
  {% if form.errors %}
    <p style="color: red">Invalid username or password. Please try again.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Log in</button>
    <a href="{% url 'cars:signup' %}">New to My Site? Sign up</a>
  </form>
{% endblock %}

form/templates/rentals/index.html
{% extends 'base/index.html' %}

{% block content %}
    {% if vehicles %}
        {% for vehicle in vehicles %}
            <div class="row">
                <div class="col s12 m6">
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title">{{ vehicle.make }}</span>
                            <p>
                                {{ vehicle.model }} vehicle at {{ vehicle.mileage }} miles.
                            </p>
                            <p>
                                Rented on: {{ vehicle.start_date }}
                            </p>
                            <p>
                                Due back on: {{ vehicle.return_date }}
                            </p>
                            <p>
                                {% if vehicle.start_date < today and vehicle.return_date > today %}
                                    <div class=''>You have {{ today|timesince:vehicle.return_date }} left on this rental.</div>
                                {% elif vehicle.return_date < today %}
                                    <div class='red-text'>This vehicle is {{ vehicle.return_date|timesince:today }} past due!</div>
                                {% endif %}
                            </p>
                        </div>
                        <div class="card-action">
                            <button class='modal-trigger' href='#return_modal_{{ vehicle.id }}'>Return This</button>
                        </div>
                        <div id='return_modal_{{ vehicle.id }}' class='modal'>
                            <div class='modal-content'>
                                <h4>Enter your return mileage:</h4>
                                <form action={% url 'cars:return' vehicle_id=vehicle.id %} method='post'>
                                    {% csrf_token %}
                                    <input type='hidden' name='start_mileage' value="{{ vehicle.mileage }}"/>
                                    <input type='hidden' name='price' value="{{ vehicle.model.rental_price }}"/>
                                    <input type='hidden' name='start_date' value="{{ vehicle.start_date }}"/>
                                    <input type='hidden' name='return_date' value="{{ vehicle.return_date }}"/>
                                    <div class='row'>
                                        <div class='col s6 offset-s3'>
                                            <h4>Your Total</h4>
                                            <div class=' green-text total'>
                                                test
                                            </div>
                                        </div>
                                        <br/><br/><br/><br/><br/>
                                        <div class='col s6 offset-s3'>
                                            <div class='input-field'>
                                                <input type='number' min="{{ vehicle.mileage }}" id='return_mileage_{{ vehicle.id }}' class='return_mileage' name='return_mileage' placeholder="{{ vehicle.mileage }}">
                                                <label for='return_mileage'>Mileage</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class='row'>
                                        <div class='col s1 offset-s8'>
                                            <input type='hidden' name='vehicle_choice' value="{{ vehicle.id }}" />
                                            <div class='modal-footer'>
                                                <input type='submit' value='Return This'>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>You haven't rented any cars.</p>
    {% endif %}
{% endblock %}

form/templates/signup/index.html
{% extends 'base/index.html' %}

{% block content %}
    <h2>Sign Up</h2>
    <form method='post'>
        {% csrf_token %}
        {% for field in form %}
            <div>
                {{ field.label_tag }}<br/>
                {{ field }}
                {% if field.help_text %}
                    <small style='color:grey'>{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style='color:red'>{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}
        <button type='submit'>Sign up</button>
    </form>
{% endblock %}

form/templates/vehicle/index.html
{% extends 'base/index.html' %}

{% block content %}
    <h2>{{ vehicle.make }}</h2>
    <p>
        Currently {{ vehicle.mileage }} miles.
    </p>
    <p>
        Rate: ${{ model.rental_price }} per day.
    </p>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action={% url 'cars:rent' model_id=model.id vehicle_id=vehicle.id %} method='post'>
        {% csrf_token %}
        <input type='hidden' name='vehicleChoice' value={{ vehicle.id }} />
        <input type='submit' value='rent'>
    </form>
{% endblock %}

form/templates/vehicles/index.html
{% extends 'base/index.html' %}

{% block content %}
    {% load custom_filters %}
    {% if vehicles %}
    <div class="row">
        <div class="col s12 m6">
            <div class='red-text'>*All vehicles have a charge of $0.32 per mile.</div>
        </div>
    </div>
    {% for vehicle in vehicles %}
        {% if vehicle.available %}
            <div class="row">
                <div class="col s12 m6">
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title">{{ vehicle.make }}</span>
                            <p>
                                Has {{ vehicle.mileage }} miles
                            </p>
                            <p>
                                {{ vehicle.model }} vehicle : ${{ model.rental_price }}/day
                            </p>
                        </div>
                        <form class='rent-form' action={% url 'cars:rent' model_id=model.id vehicle_id=vehicle.id %} method='post'>
                            {% csrf_token %}
                            <div class='input-field'>
                                <div class='row'>
                                    <div class='col s6 offset-s1'>
                                        <div class='input-field'>
                                            <input id='end_date_{{ vehicle.id }}' name='return_date' type='text' class="datepicker end_date">
                                            <label for='end_date'>Return Date</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-action">
                                <div class='row'>
                                    <div class='col'>
                                        <button class='modal-trigger return-modal' href='#rent_modal_{{ vehicle.id }}'>See rates</button>
                                    </div>
                                </div>
                            </div>
                            <div id='rent_modal_{{ vehicle.id }}' class='modal'>
                                <div class='modal-content'>
                                    <h4>Cost before mileage:</h4>
                                    <p class='number_of_days red-text'>
                                        Please select a return date!
                                    </p>
                                    <input type='hidden' name='vehicle_price' value={{ model.rental_price }}>
                                    <input type='hidden' name='vehicle_choice' value={{ vehicle.id }}>
                                    <br/><br/>
                                    <input type='submit' value='Rent This'>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
    {% else %}
        <p>No Cars are available.</p>
    {% endif %}
{% endblock %}